name: Check and Upload to Databricks

on:
  push:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.5.*'

jobs:
  check-upload:
    environment: deploy_azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python with dependencies
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Static checks
        run: make checks

      - name: Unit tests
        run: make pytest_ci

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ github.sha }}
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Upload notebooks to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD }}
          DATABRICKS_AUTH_TYPE: "pat"
        run: poetry run python3 src/scripts/upload_notebooks.py

      - name: Build and upload Python lib to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD }}
          DATABRICKS_AUTH_TYPE: "pat"
        run: poetry run python3 src/scripts/build_upload_lib.py

      - name: Deploy Prefect Flows to Prefect Cloud
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: for FILE in src/flows/*.py; do poetry run python3 $FILE; done  # todo: make separate deployment
