name: Upload files to Databricks

on:
  push:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.5.*'

jobs:

  check-upload:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python with dependencies
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      # run checks
      - name: Static checks
        run: make checks

      # run tests
      - name: Unit tests
        run: make pytest_ci

      # run upload notebooks to Databricks
      - name: Upload notebooks to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
          DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD }}
        run: poetry run python3 src/scripts/upload_notebooks.py
