name: Checks and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.5.*'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install -U poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'

      - name: Set Poetry environment
        run: poetry env use ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install --no-interaction

      # run checks
      - name: Static checks
        run: make checks

      # run tests
      - name: Unit tests
        run: make pytest_ci
