name: Upload files to Databricks

on:
  workflow_run:
    workflows: [ "Checks and Tests" ]
    branches: [ master ]
    types: [ completed ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.5.*'

jobs:
  uploads:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install -U poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'

      - name: Set Poetry environment
        run: poetry env use ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: poetry install --no-interaction

      # run upload notebooks to Databricks
      - name: Upload notebooks to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
          DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD }}
        run: poetry run python3 src/scripts/upload_notebooks.py
